name: "Proof::pypi"
on: [push]
jobs:
  proof:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Build docker image
        run: |
          docker build . -t artipie
      - name: Start python example and proof it works
        run: |
          cd examples/pypi
          sed -i 's+artipie/artipie:latest+artipie+' run.sh
          ./run.sh